import Link from "next/link";
import { ArrowRight, CalendarDays, ChartNoAxesCombined, Clock3, UsersRound } from "lucide-react";
import type { professionalReport } from "@/lib/professional-reporting";
import { bookingMoney } from "@/lib/booking-format";

type Report = Awaited<ReturnType<typeof professionalReport>>;
export function ProfessionalDashboard({ name, report, currency, bookingLimit, bookingUsed }: {
  name: string; report: Report; currency: string; bookingLimit: number; bookingUsed: number;
}) {
  const ranked = report.utilization.resources.filter(item => item.percent !== null)
    .sort((a, b) => (b.percent ?? 0) - (a.percent ?? 0));
  return <div className="foundation-page pro-dashboard"><header className="pro-page-head"><div><p className="eyebrow">BUSINESS OVERVIEW / PROFESSIONAL</p><h1>Good to see you, {name}</h1><p>Here’s how your venue is doing this month.</p></div><div className="starter-head-actions"><Link className="button button-secondary" href="/reports">Explore reports</Link><Link className="button button-primary" href="/bookings/new">New booking</Link></div></header>
    <div className="pro-dashboard-period"><CalendarDays size={16} /> {report.fromDate} – {report.toDate} · {report.timezone}</div>
    <section className="pro-metrics" aria-label="Revenue this month"><div className="pro-metric"><span>Booking value</span><strong>{bookingMoney(report.totals.bookingValue, currency)}</strong><small>Confirmed and fulfilled bookings</small></div><div className="pro-metric"><span>Collected</span><strong>{bookingMoney(report.totals.collected, currency)}</strong><small>Net paid against these bookings</small></div><div className="pro-metric"><span>Outstanding</span><strong>{bookingMoney(report.totals.outstanding, currency)}</strong><small>Still due on active bookings</small></div><div className="pro-metric"><span>Refunds</span><strong>{bookingMoney(report.totals.refunds, currency)}</strong><small>Succeeded refunds for these bookings</small></div></section>
    <div className="pro-two-columns"><section className="foundation-card pro-panel"><div className="pro-panel-head"><div><p className="eyebrow">BOOKING PERFORMANCE</p><h2>At a glance</h2></div><Link href="/reports?section=bookings">See trends <ArrowRight size={15} /></Link></div><div className="pro-outcomes"><div className="pro-metric"><span>Bookings</span><strong>{report.totals.bookings}</strong></div><div className="pro-metric"><span>Completed</span><strong>{report.totals.completed}</strong></div><div className="pro-metric"><span>Cancelled</span><strong>{report.totals.cancelled}</strong><small>{report.totals.cancellationRate ?? "—"}% of bookings</small></div><div className="pro-metric"><span>No-shows</span><strong>{report.totals.noShows}</strong><small>{report.totals.noShowRate ?? "—"}% of confirmed bookings</small></div></div></section>
      <section className="foundation-card pro-panel"><div className="pro-panel-head"><div><p className="eyebrow">VENUE CAPACITY</p><h2>Space utilisation</h2></div><Link href="/reports?section=resources">View spaces <ArrowRight size={15} /></Link></div><div className="pro-feature-number">{report.utilization.percent === null ? "—" : `${report.utilization.percent}%`}</div><div className="pro-dashboard-duo"><span>Busiest <strong>{ranked[0]?.name ?? "—"}</strong></span><span>Quietest <strong>{ranked.at(-1)?.name ?? "—"}</strong></span></div><p className="pro-note">Booked time as a share of usable opening time, after blocks and maintenance.</p></section></div>
    <div className="pro-dashboard-trio"><Link className="foundation-card pro-panel" href="/reports?section=customers"><UsersRound size={20} /><span>Customers</span><strong>{report.customers.new} new · {report.customers.returning} returning</strong><small>{report.customers.returningRate ?? "—"}% returning rate</small></Link>
      <Link className="foundation-card pro-panel" href="/reports?section=resources"><Clock3 size={20} /><span>Peak period</span><strong>{report.peak.day ?? "Not enough data"}</strong><small>{report.peak.period ?? "Bookings will reveal your busiest time"}</small></Link>
      <Link className="foundation-card pro-panel" href="/settings/plan"><ChartNoAxesCombined size={20} /><span>Plan usage</span><strong>{bookingUsed} / {bookingLimit} bookings</strong><small>First confirmations this UTC month</small></Link></div>
    <p className="pro-note">Insights are based on real booking records. Collected is attributed to booking date, not a cash-flow statement. No comparison is shown until equivalent historical data is available.</p>
  </div>;
}
